# Generated by Django 2.1.2 on 2018-11-04 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='Images/No-img.jpg', upload_to='Images/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('people', 'People'), ('nature', 'Nature'), ('city_life', 'City Life'), ('love', 'Love'), ('sport', 'Sport'), ('family', 'Family')], default='nature', max_length=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
